---
apiVersion: v1
kind: PersistentVolume 
metadata:
  name: postgres-volume
  labels:
    type: local 
    app: postgres
spec:
  storageClassName: default
  capacity:
    storage: 10Gi 
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/postgresql"